# Generated by Django 4.2.2 on 2023-06-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleSaude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.BigIntegerField(max_length=3)),
                ('cpf', models.BigIntegerField(max_length=11)),
                ('data', models.DateTimeField(max_length=10)),
                ('horario', models.TimeField(max_length=5)),
                ('motivo', models.CharField(max_length=50)),
            ],
        ),
    ]
