# Generated by Django 4.2.2 on 2023-06-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleSaude', '0002_agendamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='data',
            field=models.DateField(max_length=10),
        ),
    ]
